//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FGU { get; set; }
        public string Email { get; set; }
        public System.Guid id { get; set; }
    }
}
