// <auto-generated />
namespace Gefco.CipQuai.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addsomemore2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addsomemore2));
        
        string IMigrationMetadata.Id
        {
            get { return "201905231610416_Add some more 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
