// <auto-generated />
namespace Gefco.CipQuai.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddAgenceIsProvenanceNC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddAgenceIsProvenanceNC));
        
        string IMigrationMetadata.Id
        {
            get { return "201905230652058_Add Agence.IsProvenanceNC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
