// <auto-generated />
namespace Gefco.CipQuai.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddNonConformitesAgenceConcernee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNonConformitesAgenceConcernee));
        
        string IMigrationMetadata.Id
        {
            get { return "201904301132370_Add NonConformites.AgenceConcernee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
