// <auto-generated />
namespace Gefco.CipQuai.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddDeclarationNCNumVoyage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDeclarationNCNumVoyage));
        
        string IMigrationMetadata.Id
        {
            get { return "201906011132077_Add DeclarationNC.NumVoyage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
